<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1412949538848" stop="1412949560045"
                version="1.4.4-SNAPSHOT">
    <name>my.company.Sample</name>
    <test-cases>
        <test-case start="1412949539363" stop="1412949539730" status="passed">
            <name>sampleTestCase</name>
            <labels>
                <label name="issue" value="issue-123"/>
            </labels>
        </test-case>
        <test-case start="1495987564304" stop="1495987564321" status="failed">
            <name>simpleFaildTest</name>
            <failure>
                <message>AssertionError:
                    Expected: is &lt;3&gt;
                    but: was &lt;2&gt;</message>
                <stack-trace>java.lang.AssertionError:
                    Expected: is &lt;3&gt;
                    but: was &lt;2&gt;
                    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
                    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
                    at my.company.tests.SimpleTest.simpleFaildTest(SimpleTest.java:51)
                    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                    at java.lang.reflect.Method.invoke(Method.java:497)
                    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
                    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
                    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
                    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
                    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
                    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
                    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
                </stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="issue" value="issue-234"/>
            </labels>
        </test-case>
    </test-cases>
</ns2:test-suite>
